# TCL File Generated by Component Editor 13.1
# Mon Sep 24 13:53:43 BRT 2018
# DO NOT MODIFY


# 
# lcdshow "lcdshow" v1.0
#  2018.09.24.13:53:43
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module lcdshow
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcdshow
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcdshow
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file conexaoLCD.v VERILOG PATH ../../../../Desktop/conexaoLCD.v


# 
# parameters
# 


# 
# display items
# 

